const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const root = path.resolve(__dirname, "..");
const sourceRoot = path.join(root, "src");
const distRoot = path.join(root, "dist");
const entryPath = path.join(sourceRoot, "index.js");
const packageJson = JSON.parse(
    fs.readFileSync(path.join(root, "package.json"), "utf8")
);
const banner = `/*! Timeline Reprise v${packageJson.version} | Generated by npm run build */`;

function readText(filename) {
    return fs.readFileSync(filename, "utf8").replace(/\r\n/g, "\n").trim();
}

function toSourcePath(filename) {
    return path.relative(sourceRoot, filename).replace(/\\/g, "/");
}

function resolveSourcePath(fromFile, specifier) {
    if (!specifier.startsWith("./") && !specifier.startsWith("../")) {
        throw new Error(`Only relative source imports are supported: ${specifier}`);
    }

    const filename = path.resolve(path.dirname(fromFile), specifier);
    const sourcePrefix = sourceRoot + path.sep;

    if (filename !== sourceRoot && !filename.startsWith(sourcePrefix)) {
        throw new Error(`Source path escapes src/: ${specifier}`);
    }
    if (!fs.existsSync(filename)) {
        throw new Error(`Distribution source does not exist: ${filename}`);
    }

    return {
        path: toSourcePath(filename),
        filename
    };
}

function readScriptEntries(entryText) {
    const importPattern = /^import\s+(?:[^'"]+\s+from\s+)?['"]([^'"]+\.js)['"]\s*;?\s*$/gm;
    const entries = Array.from(entryText.matchAll(importPattern), match =>
        resolveSourcePath(entryPath, match[1])
    );

    if (entries.length === 0) {
        throw new Error(`No JavaScript imports found in ${entryPath}`);
    }

    return entries;
}

function readStylesheetEntries(entryText) {
    const match = entryText.match(
        /export\s+const\s+stylesheets\s*=\s*(\[[\s\S]*?\])\s*;/m
    );

    if (!match) {
        throw new Error(`No stylesheets export found in ${entryPath}`);
    }

    const stylesheets = JSON.parse(match[1]);

    if (!Array.isArray(stylesheets) || stylesheets.length === 0) {
        throw new Error("The stylesheets export must be a non-empty array");
    }

    return stylesheets.map(specifier => {
        if (typeof specifier !== "string" || !specifier.endsWith(".css")) {
            throw new Error(`Invalid stylesheet source: ${specifier}`);
        }

        return resolveSourcePath(entryPath, specifier);
    });
}

function combine(entries) {
    return [
        banner,
        ...entries.map(entry => `/* ${entry.path} */\n${readText(entry.filename)}`)
    ].join("\n\n") + "\n";
}

function copyCssAssets(cssEntries) {
    const copiedTargets = new Map();
    const urlPattern = /url\(\s*(['"]?)([^'")]+)\1\s*\)/g;

    for (const entry of cssEntries) {
        const css = readText(entry.filename);

        for (const match of css.matchAll(urlPattern)) {
            const assetPath = match[2];
            if (/^(?:[a-z]+:|\/|#)/i.test(assetPath)) continue;

            const source = path.resolve(path.dirname(entry.filename), assetPath);
            const target = path.resolve(distRoot, assetPath);
            const distPrefix = distRoot + path.sep;

            if (!target.startsWith(distPrefix)) {
                throw new Error(`CSS asset escapes dist/: ${assetPath}`);
            }
            if (!fs.existsSync(source)) {
                throw new Error(`CSS asset does not exist: ${source}`);
            }

            const previousSource = copiedTargets.get(target);
            if (previousSource != null) {
                if (!fs.readFileSync(previousSource).equals(fs.readFileSync(source))) {
                    throw new Error(`Conflicting CSS assets target ${target}`);
                }
                continue;
            }

            fs.mkdirSync(path.dirname(target), { recursive: true });
            fs.copyFileSync(source, target);
            copiedTargets.set(target, source);
        }
    }

    return copiedTargets.size;
}

const entryText = readText(entryPath);
const scriptEntries = readScriptEntries(entryText);
const cssEntries = readStylesheetEntries(entryText);
const js = combine(scriptEntries);
const css = combine(cssEntries);

new vm.Script(js, { filename: "dist/timeline-reprise.js" });

fs.rmSync(distRoot, { recursive: true, force: true });
fs.mkdirSync(distRoot, { recursive: true });
fs.writeFileSync(path.join(distRoot, "timeline-reprise.js"), js, "utf8");
fs.writeFileSync(path.join(distRoot, "timeline-reprise.css"), css, "utf8");

const assetCount = copyCssAssets(cssEntries);

console.log(
    `Built dist/timeline-reprise.js, dist/timeline-reprise.css, and ${assetCount} media assets.`
);
