const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const root = path.resolve(__dirname, "..");
const sourceRoot = path.join(root, "timeline-reprise");
const distRoot = path.join(root, "dist");
const loaderPath = path.join(sourceRoot, "timeline-reprise.js");
const packageJson = JSON.parse(
    fs.readFileSync(path.join(root, "package.json"), "utf8")
);
const banner = `/*! Timeline Reprise v${packageJson.version} | Generated by npm run build */`;

function readText(filename) {
    return fs.readFileSync(filename, "utf8").replace(/\r\n/g, "\n").trim();
}

function readManifest() {
    const loader = readText(loaderPath);
    const pattern = /\{\s*type:\s*['"](css|js)['"]\s*,\s*path:\s*['"]([^'"]+)['"]\s*\}/g;
    const entries = Array.from(loader.matchAll(pattern), match => ({
        type: match[1],
        path: match[2]
    }));

    if (entries.length === 0) {
        throw new Error(`No distribution entries found in ${loaderPath}`);
    }

    for (const entry of entries) {
        const filename = path.join(sourceRoot, entry.path);
        if (!fs.existsSync(filename)) {
            throw new Error(`Distribution source does not exist: ${filename}`);
        }
    }

    return entries;
}

function combine(entries, type) {
    return [
        banner,
        ...entries
            .filter(entry => entry.type === type)
            .map(entry => `/* ${entry.path} */\n${readText(path.join(sourceRoot, entry.path))}`)
    ].join("\n\n") + "\n";
}

function copyCssAssets(cssEntries) {
    const copiedTargets = new Map();
    const urlPattern = /url\(\s*(['"]?)([^'")]+)\1\s*\)/g;

    for (const entry of cssEntries) {
        const cssFile = path.join(sourceRoot, entry.path);
        const css = readText(cssFile);

        for (const match of css.matchAll(urlPattern)) {
            const assetPath = match[2];
            if (/^(?:[a-z]+:|\/|#)/i.test(assetPath)) continue;

            const source = path.resolve(path.dirname(cssFile), assetPath);
            const target = path.resolve(distRoot, assetPath);
            const distPrefix = distRoot + path.sep;

            if (!target.startsWith(distPrefix)) {
                throw new Error(`CSS asset escapes dist/: ${assetPath}`);
            }
            if (!fs.existsSync(source)) {
                throw new Error(`CSS asset does not exist: ${source}`);
            }

            const previousSource = copiedTargets.get(target);
            if (previousSource != null) {
                if (!fs.readFileSync(previousSource).equals(fs.readFileSync(source))) {
                    throw new Error(`Conflicting CSS assets target ${target}`);
                }
                continue;
            }

            fs.mkdirSync(path.dirname(target), { recursive: true });
            fs.copyFileSync(source, target);
            copiedTargets.set(target, source);
        }
    }

    return copiedTargets.size;
}

const entries = readManifest();
const js = combine(entries, "js");
const css = combine(entries, "css");

if (!entries.some(entry => entry.type === "js")) {
    throw new Error("The distribution manifest contains no JavaScript sources");
}
if (!entries.some(entry => entry.type === "css")) {
    throw new Error("The distribution manifest contains no CSS sources");
}

new vm.Script(js, { filename: "dist/timeline-reprise.js" });

fs.rmSync(distRoot, { recursive: true, force: true });
fs.mkdirSync(distRoot, { recursive: true });
fs.writeFileSync(path.join(distRoot, "timeline-reprise.js"), js, "utf8");
fs.writeFileSync(path.join(distRoot, "timeline-reprise.css"), css, "utf8");

const assetCount = copyCssAssets(entries.filter(entry => entry.type === "css"));

console.log(
    `Built dist/timeline-reprise.js, dist/timeline-reprise.css, and ${assetCount} media assets.`
);
